# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  azureSubscription: 'AzureConnection'

pool:
  vmImage: ubuntu-latest

stages:

- stage: deploy
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy bicep to Azure'
    environment: 'AzureDeployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: 'MS MSDN Account(ca001e53-0237-4d8b-b28e-7e9be5757de4)' 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub create  -f  $(System.DefaultWorkingDirectory)/hubSpoke.bicep --location westeurope